### ISSUE TITLE
zcash_client_sqlite always enables the "orchard" feature of zcash_keys

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#1488]
From `zcash_client_sqlite`'s `Cargo.toml`:

```toml
[dependencies]
...
zcash_keys = { workspace = true, features = ["orchard", "sapling"] }

[features]
...
orchard = ["dep:orchard", "zcash_client_backend/orchard", "zcash_keys/orchard"]
```
This will always enable the "orchard" feature of zcash_keys, because "orchard" is specified unconditionally in `[dependencies]` (so the conditional feature dependency in `[features]` is redundant). I've verified this using `cargo -v` to show the `rustc` command lines.

Intentional or bug?
